package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.function.Supplier;

import org.opencv.core.Mat;

import edu.wpi.first.apriltag.AprilTagFieldLayout;
import edu.wpi.first.apriltag.AprilTagFields;
import edu.wpi.first.apriltag.jni.*;
import edu.wpi.first.hal.simulation.AddressableLEDDataJNI;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.configs.CurrentLimitsConfigs;
import com.ctre.phoenix6.configs.TalonFXConfigurator;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.controller.HolonomicDriveController;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.controller.ProfiledPIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Pose3d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.SwerveDriveKinematics;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.trajectory.TrapezoidProfile;
import edu.wpi.first.units.ResistanceUnit;
import edu.wpi.first.units.measure.Distance;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Constants;
import frc.robot.LimelightHelpers;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    PIDController aimingPidController = new PIDController(5, 0, 0);
    private  Constants m_Constants = new Constants();
    private double lastTag = 1;


    //Autoalign stuff here
    private List<Pose2d> poseList = new ArrayList<>();
    private boolean isAtAngleTest = false;
    public static Pose2d idealPose = new Pose2d(); 
    TalonFXConfigurator config2 = getModule(1).getDriveMotor().getConfigurator();
    TalonFXConfigurator config3 = getModule(2).getDriveMotor().getConfigurator();
    TalonFXConfigurator config4 = getModule(3).getDriveMotor().getConfigurator();
    TalonFXConfigurator config1 = getModule(0).getDriveMotor().getConfigurator();

    CurrentLimitsConfigs limitConfigs = new CurrentLimitsConfigs();

    // enable stator current limit
    private PIDController transController = new PIDController(5.5, 0, 0.001);
    private ProfiledPIDController rotController = new ProfiledPIDController(2.45, 0, 0.001, 
    new TrapezoidProfile.Constraints(360, 720));
    private HolonomicDriveController alignFinalController = new HolonomicDriveController(transController,transController, rotController);
    private static final double kSimLoopPeriod = 0.005; // 5 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;
    private final Field2d field = new Field2d();
    private final boolean kUseLimelight = true;

    private PPHolonomicDriveController ppcontroller = new PPHolonomicDriveController(
    // PID constants for translation
    new PIDConstants(6, 0, 0.01),
    // PID constants for rotation
    new PIDConstants(5, 0, 0.01));

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;
    
    /** Swerve request to apply during robot-centric path following */
    private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();



    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
        alignFinalController.setTolerance(new Pose2d(.25, .25, new Rotation2d()));
        SmartDashboard.putData("Field", field);
        alignFinalController.getXController().setTolerance(.5);
        transController.setTolerance(.035);
        
        limitConfigs.StatorCurrentLimit = 55;
        limitConfigs.StatorCurrentLimitEnable = true;
        config1.apply(limitConfigs);
        config2.apply(limitConfigs);
        config3.apply(limitConfigs);
        config4.apply(limitConfigs);
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        this.setVisionMeasurementStdDevs(VecBuilder.fill(.7,.7,999999999));
        SmartDashboard.putData("Field", field);
        configureAutoBuilder(); 
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }


    private void configureAutoBuilder() {
        try {
            var config = RobotConfig.fromGUISettings();
            AutoBuilder.configure(
                () -> getState().Pose,   // Supplier of current robot pose
                this::resetPose,         // Consumer for seeding pose against auto
                () -> getState().Speeds, // Supplier of current robot speeds
                // Consumer of ChassisSpeeds and feedforwards to drive the robot
                (speeds, feedforwards) -> setControl(
                    m_pathApplyRobotSpeeds.withSpeeds(speeds)
                        .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                        .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())
                ),
                ppcontroller,
                config,
                // Assume the path needs to be flipped for Red vs Blue, this is normally the case
                () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
                this // Subsystem for requirements
            );
        } catch (Exception ex) {
            DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
        }
    }
    private void ll3gPose(){
        
        if (kUseLimelight) {

            LimelightHelpers.SetRobotOrientation("limelight-good", getState().Pose.getRotation().getDegrees(), 0, 0, 0, 0, 0);
            var llMeasurement = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2("limelight-good");
            if (llMeasurement != null && llMeasurement.tagCount>=1) {
              field.setRobotPose(llMeasurement.pose); 
              
              SmartDashboard.putNumber("LL3GDistance", llMeasurement.avgTagDist);
              if(llMeasurement.avgTagDist<=2){

              addVisionMeasurement(llMeasurement.pose, Utils.fpgaToCurrentTime(llMeasurement.timestampSeconds));}
            }
          }
    }
  

   private void llFeederPose(){
    if (kUseLimelight) {

        LimelightHelpers.SetRobotOrientation("limelight-good", getState().Pose.getRotation().getDegrees(), 0, 0, 0, 0, 0);
        var llMeasurement = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2("limelight-good");
        
        if (llMeasurement != null && llMeasurement.tagCount>=1 ) {
            SmartDashboard.putNumber("FeederTagDistance", llMeasurement.avgTagDist);
            if(llMeasurement.avgTagDist<=1.2){

          addVisionMeasurement(llMeasurement.pose, Utils.fpgaToCurrentTime(llMeasurement.timestampSeconds));}
        }
        
      }
    }

    public Rotation2d getHUbRotation2d(){
        Rotation2d HUB;
        Boolean allianceBlue = DriverStation.getAlliance().get() == Alliance.Blue;
        if (allianceBlue){
            Pose2d hubPose = Constants.hubPositionBLUE.BlueHub;
            Translation2d relativeTrl= hubPose.relativeTo(new Pose2d()).getTranslation();
             HUB = new Rotation2d(relativeTrl.getX(),relativeTrl.getY()).plus(getHeading());
        }
        else {
            Pose2d hubPose = Constants.hubPositionRED.RedHub;
            Translation2d relativeTrl= hubPose.relativeTo(new Pose2d()).getTranslation();
             HUB = new Rotation2d(relativeTrl.getX(),relativeTrl.getY()).plus(getHeading());
        }
        return HUB;       
    }


    public Rotation2d getHubYaw(){
        AprilTagFieldLayout aprilTagFieldLayout = AprilTagFields.k2025ReefscapeWelded.loadAprilTagLayoutField();
        int allianceAprilTag = DriverStation.getAlliance().get() == Alliance.Blue ? 10 : 25;

        Pose3d hubAprilTagPose = aprilTagFieldLayout.getTagPose(allianceAprilTag).get();
        Translation2d relativeTrl = hubAprilTagPose.toPose2d().relativeTo(new Pose2d()).getTranslation();
        return new  Rotation2d(relativeTrl.getX(),relativeTrl.getY()).plus(getHeading());
    }

    public Pose2d pose_limelight(){
        return LimelightHelpers.getBotPose2d("light-line");
    }



    public double aimHub(){
        aimingPidController.enableContinuousInput(-180, 180);
        return(aimingPidController.calculate(getHeading().getDegrees(), getHUbRotation2d().getDegrees()));
    }

    private Rotation2d getHeading(){
        return getState().Pose.getRotation();
    }

    public double aimAt(double angle){
        aimingPidController.enableContinuousInput(-180, 180);
    return (aimingPidController.calculate(getHeading().getDegrees(), angle));
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> requestSupplier) {
        return run(() -> this.setControl(requestSupplier.get()));
    }


    @Override
    public void periodic() {
        SmartDashboard.putNumber("Battery Voltage", RobotController.getBatteryVoltage());
        SmartDashboard.putNumber("Brownout Voltage", RobotController.getBrownoutVoltage());
        SmartDashboard.putNumber("Angle Robot", getState().Pose.getRotation().getDegrees());
        SmartDashboard.putBoolean("isAtReference", alignFinalController.atReference());
        SmartDashboard.putNumber("Angle_HUB", getHUbRotation2d().getDegrees());
        SmartDashboard.putNumber("outup_PID_yaw", aimHub());
        SmartDashboard.putString("Alliance Rojo", DriverStation.getAlliance().get().toString());
    //    rumble(RobotContainer.driverHID, RobotContainer.opHID);
        ll3gPose();
        llFeederPose();








        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }
}
